version: '2'
services:
  services:
    build: .
    env_file: secrects.env
    environment:
      - VIRTUAL_HOST=mh.bewegung.jetzt
      - LETSENCRYPT_HOST=mh.bewegung.jetzt
      - LETSENCRYPT_EMAIL=tech@bewegung.jetzt
    volumes:
      - ./data/syncer:/code/data
    restart: unless-stopped
    expose:
     - 5000
  db:
    image: couchdb:latest
    environment:
      - VIRTUAL_HOST=cllctrdb.bewegung.jetzt
      - LETSENCRYPT_HOST=cllctrdb.bewegung.jetzt
      - LETSENCRYPT_EMAIL=tech@bewegung.jetzt
    env_file: secrects.env
    volumes:
       - ./data/couchdb-config:/usr/local/etc/couchdb/local.d/
       - ./data/db:/usr/local/var/lib/couchdb/
    expose:
      - 5984
    restart: unless-stopped
  web:
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=swk.bewegung.jetzt
      - LETSENCRYPT_HOST=swk.bewegung.jetzt
      - LETSENCRYPT_EMAIL=tech@bewegung.jetzt
      - NGINX_HOST=swk.bewegung.jetzt
      - NGINX_PORT=80
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    expose:
      - 80
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy
