version: '2'
services:
  db:
    image: couchdb
    environment:
      - VIRTUAL_HOST=cllctrdb.bewegung.jetzt
      - LETSENCRYPT_HOST_DOMAIN=cllctrdb.bewegung.jetzt
      - LETSENCRYPT_EMAIL=tech@bewegung.jetzt
    env_file: secrects.env
    volumes:
       - ./data/db:/usr/local/var/lib/couchdb
    expose:
      - 5984
    restart: unless-stopped
  web:
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=swk.bewegung.jetzt
      - LETSENCRYPT_HOST=swk.bewegung.jetzt
      - LETSENCRYPT_EMAIL=tech@bewegung.jetzt
      - NGINX_HOST=swk.bewegung.jetzt
      - NGINX_PORT=80
    volumes:
      - ./build:/usr/share/nginx/html:ro
    expose:
      - 80
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy
